"""
Phase 6 — Final Feedback Report generation.

Aggregates all interview session data into a single structured report:
  - Technical score (blended from all evaluated answers)
  - Behavioral scores (communication, confidence, engagement) as *placeholders*
    derived from simple answer heuristics; marked with behavioral_mode="placeholder"
    until audio/video analysis is added in a later phase.
  - Role fit score (from stored role-recommendation results)
  - Strengths and improvement areas extracted from covered/missing points
  - Personalised learning plan mapped from weak topics to curated resources
  - Final feedback generated by LLM (if available) or rule-based template

Overall Score = technical×0.45 + communication×0.20 + confidence×0.15
              + engagement×0.10 + role_fit×0.10
"""

import logging
from datetime import datetime, timezone
from statistics import mean

from models.interview import FinalReport, AnswerSummary, LearningItem

logger = logging.getLogger(__name__)

_MAX_STRENGTHS    = 5
_MAX_IMPROVEMENTS = 5
_MAX_LEARNING     = 6

# ── Curated topic → resource mapping ─────────────────────────────────────────

_TOPIC_RESOURCES: dict[str, dict] = {
    "REST Fundamentals": {
        "resource": "restfulapi.net free reference + REST API Design Rulebook (O'Reilly)",
        "reason":   "Solidify statelessness, HTTP semantics, status codes, and resource modelling.",
        "priority": "high",
    },
    "Database Design": {
        "resource": "CMU 15-445 Database Systems — free on YouTube (Prof. Andy Pavlo)",
        "reason":   "Deep-dive into indexing, ACID, query optimisation, and schema design patterns.",
        "priority": "high",
    },
    "Authentication": {
        "resource": "OAuth 2.0 in Action (Manning) + auth0.com developer docs",
        "reason":   "Master token flows, refresh token rotation, and secure storage strategies.",
        "priority": "high",
    },
    "Security": {
        "resource": "PortSwigger Web Security Academy — free interactive labs",
        "reason":   "Hands-on practice with XSS, CSRF, SQL injection, and authentication flaws.",
        "priority": "high",
    },
    "System Design": {
        "resource": "Designing Data-Intensive Applications — Martin Kleppmann (O'Reilly)",
        "reason":   "The definitive guide to distributed systems, consistency, and scalability.",
        "priority": "high",
    },
    "Performance Optimization": {
        "resource": "Chrome DevTools Performance Guide + Web Performance in Action (Manning)",
        "reason":   "Profiling, caching strategies, and full-stack bottleneck diagnosis.",
        "priority": "medium",
    },
    "Frontend Architecture": {
        "resource": "Patterns.dev — free book on modern JavaScript and React design patterns",
        "reason":   "State management, component design, and rendering strategies in depth.",
        "priority": "medium",
    },
    "React Internals": {
        "resource": "react.dev official docs — Hooks, reconciliation, and concurrent features",
        "reason":   "First-party deep-dive into Virtual DOM, hooks internals, and performance APIs.",
        "priority": "medium",
    },
    "CSS Fundamentals": {
        "resource": "Josh Comeau's CSS for JavaScript Developers (joshwcomeau.com)",
        "reason":   "Modern CSS — cascade, layout modes, custom properties, and animation.",
        "priority": "low",
    },
    "Rendering Strategies": {
        "resource": "Next.js documentation — SSR, SSG, ISR, and App Router",
        "reason":   "Practical examples of all rendering modes with trade-off guidance.",
        "priority": "medium",
    },
    "Accessibility": {
        "resource": "Deque University free WCAG course + axe-core integration guide",
        "reason":   "ARIA patterns, keyboard navigation, and automated accessibility testing.",
        "priority": "medium",
    },
    "Error Handling": {
        "resource": "Release It! — Michael Nygard (Pragmatic Programmers)",
        "reason":   "Circuit breakers, timeouts, bulkheads, and production resilience patterns.",
        "priority": "medium",
    },
    "API Design": {
        "resource": "API Design Patterns — JJ Geewax (Manning)",
        "reason":   "Idempotency, pagination, versioning, webhooks, and error response design.",
        "priority": "high",
    },
    "Database": {
        "resource": "CMU 15-445 Database Systems — free on YouTube (Prof. Andy Pavlo)",
        "reason":   "Transactions, isolation levels, indexing strategies, and query optimisation.",
        "priority": "high",
    },
    "Concurrency": {
        "resource": "Python Concurrency with asyncio — Matthew Fowler (Manning)",
        "reason":   "asyncio, threading, multiprocessing, and concurrent design patterns.",
        "priority": "medium",
    },
    "Observability": {
        "resource": "Honeycomb.io Observability Engineering (free PDF) + OpenTelemetry docs",
        "reason":   "Distributed tracing, structured logging, SLI/SLO-based alerting.",
        "priority": "medium",
    },
    "Kubernetes": {
        "resource": "Kubernetes in Action (Manning) + Kelsey Hightower's k8s the Hard Way",
        "reason":   "Scheduling, networking, StatefulSets, and production operations.",
        "priority": "high",
    },
    "Cloud Architecture": {
        "resource": "AWS Solutions Architect Associate — Stephane Maarek (Udemy)",
        "reason":   "Multi-region architecture, managed services, and cost-optimised designs.",
        "priority": "high",
    },
    "Model Selection": {
        "resource": "Hands-On ML with Scikit-Learn, Keras & TensorFlow — Géron (O'Reilly)",
        "reason":   "Industry-standard reference for model selection, evaluation, and tuning.",
        "priority": "high",
    },
    "Model Theory": {
        "resource": "Pattern Recognition and Machine Learning — Bishop (free PDF, Microsoft)",
        "reason":   "Rigorous treatment of bias-variance, regularisation, and probabilistic models.",
        "priority": "high",
    },
    "Practical ML": {
        "resource": "Imbalanced-learn docs + Kaggle (fraud / medical imbalanced datasets)",
        "reason":   "Hands-on practice with SMOTE, threshold tuning, and cost-sensitive learning.",
        "priority": "high",
    },
    "Experimentation": {
        "resource": "Trustworthy Online Controlled Experiments — Kohavi et al. (Cambridge UP)",
        "reason":   "Power analysis, randomisation unit selection, novelty effects, and guardrail metrics.",
        "priority": "high",
    },
    "Evaluation Metrics": {
        "resource": "Scikit-learn metrics docs + Google's ML Crash Course (free)",
        "reason":   "Precision, recall, F1, ROC-AUC, and calibration — with when to use each.",
        "priority": "medium",
    },
    "MLOps": {
        "resource": "Made With ML — madewithml.com (free end-to-end MLOps course)",
        "reason":   "Experiment tracking, CI/CD for models, deployment, and drift monitoring.",
        "priority": "high",
    },
    "Deep Learning": {
        "resource": "fast.ai Practical Deep Learning for Coders — fast.ai (free)",
        "reason":   "Top-down approach to transformers, CNNs, and modern architectures.",
        "priority": "high",
    },
    "Transfer Learning": {
        "resource": "Hugging Face course — huggingface.co/learn (free)",
        "reason":   "Fine-tuning pre-trained models with PEFT and LoRA techniques.",
        "priority": "high",
    },
    "Model Serving": {
        "resource": "vLLM documentation + BentoML production serving guides",
        "reason":   "Continuous batching, quantisation (INT4/INT8), and horizontal scaling for LLM inference.",
        "priority": "medium",
    },
    "Continual Learning": {
        "resource": "Avalanche library docs — avalanche-lib.com + EWC paper (arXiv:1612.00796)",
        "reason":   "Hands-on strategies to avoid catastrophic forgetting during incremental training.",
        "priority": "low",
    },
    "Processing Paradigms": {
        "resource": "Fundamentals of Data Engineering — Joe Reis & Matt Housley (O'Reilly)",
        "reason":   "Batch vs streaming trade-offs, Lambda/Kappa architecture, and tooling overview.",
        "priority": "high",
    },
    "Pipeline Design": {
        "resource": "Apache Flink docs + Confluent Kafka Streams tutorial (confluent.io/learn)",
        "reason":   "Watermarks, exactly-once semantics, fault tolerance, and late data handling.",
        "priority": "high",
    },
    "Data Quality": {
        "resource": "Great Expectations docs (greatexpectations.io) + dbt testing guide",
        "reason":   "Schema validation, statistical anomaly detection, and quarantine patterns.",
        "priority": "medium",
    },
    "Data Modelling": {
        "resource": "The Data Warehouse Toolkit — Ralph Kimball (star schema bible)",
        "reason":   "Fact/dimension design, SCDs, aggregate tables, and partitioning for analytics.",
        "priority": "high",
    },
    "Performance": {
        "resource": "Spark: The Definitive Guide — Chambers & Zaharia (O'Reilly)",
        "reason":   "Shuffle optimisation, partitioning strategy, broadcast joins, and Spark UI debugging.",
        "priority": "medium",
    },
    "React Native Internals": {
        "resource": "React Native New Architecture guide + Reanimated library docs",
        "reason":   "JSI, Fabric renderer, TurboModules, and eliminating bridge overhead.",
        "priority": "medium",
    },
    "Offline Architecture": {
        "resource": "Building Offline-First Apps with React Native — egghead.io",
        "reason":   "Local storage strategies, conflict resolution, and background sync queues.",
        "priority": "high",
    },
    "Platform APIs": {
        "resource": "iOS and Android push notification guides + Notifee library docs",
        "reason":   "APNs vs FCM, token lifecycle, rich notifications, and permission request flows.",
        "priority": "medium",
    },
    "Project Deep Dive": {
        "resource": "The Pragmatic Programmer — Hunt & Thomas (20th anniversary edition)",
        "reason":   "Improve how you communicate technical decisions and trade-offs under interview conditions.",
        "priority": "low",
    },
}

_GENERIC_RESOURCE = {
    "resource": "System Design Interview Vol. 1 & 2 — Alex Xu",
    "reason":   "Broad coverage of architecture, scalability, and technical communication skills.",
    "priority": "medium",
}


# ── Score helpers ─────────────────────────────────────────────────────────────

def _compute_technical_score(answers: list[dict]) -> int:
    if not answers:
        return 0
    tech  = [a["evaluation"]["technical_score"] for a in answers]
    depth = [a["evaluation"]["depth_score"]      for a in answers]
    blended = [t * 0.70 + d * 0.30 for t, d in zip(tech, depth)]
    return round(mean(blended))


def _compute_behavioral_scores(answers: list[dict]) -> tuple[int, int, int]:
    """
    Returns (communication, confidence, engagement).
    All values are heuristic proxies marked as behavioral_mode='placeholder'.
    They will be replaced by audio/video analysis in a future phase.

    Communication  — proxy: average answer word count (articulation proxy)
    Confidence     — proxy: score trajectory (improving scores → more confident delivery)
    Engagement     — proxy: number of questions answered (consistency proxy)
    """
    if not answers:
        return 72, 68, 70

    word_counts = [len(a["answer_text"].split()) for a in answers]
    avg_words   = mean(word_counts)

    # Communication: 55-85 range based on answer length
    if avg_words >= 130:
        comm = min(85, 75 + int((avg_words - 130) / 25))
    elif avg_words >= 65:
        comm = 65 + int((avg_words - 65) / 9)
    else:
        comm = max(52, 55 + int(avg_words / 5))

    # Confidence: based on score trend
    tech_series = [a["evaluation"]["technical_score"] for a in answers]
    if len(tech_series) >= 2:
        delta = tech_series[-1] - tech_series[0]
        conf  = min(85, max(52, 65 + int(delta * 0.35)))
    else:
        conf = 68

    # Engagement: questions answered (1→66, 2→70, 3→74, 4→78, 5→82)
    eng = min(84, 62 + len(answers) * 4)

    return int(comm), int(conf), int(eng)


def _get_role_fit_score(candidate_id: str, selected_role: str) -> int:
    from database import store
    roles_data = store.get_roles(candidate_id)
    if roles_data:
        for r in roles_data.get("recommended_roles", []):
            if r.get("role") == selected_role:
                return int(r.get("match_score", 72))
    return 72


# ── Qualitative analysis ──────────────────────────────────────────────────────

def _extract_strengths(answers: list[dict], analysis) -> list[str]:
    seen: set[str] = set()
    strengths: list[str] = []

    for a in answers:
        for pt in a["evaluation"].get("covered_points", []):
            key = pt.lower()[:45]
            if key not in seen:
                seen.add(key)
                strengths.append(pt)

    if analysis and hasattr(analysis, "strengths"):
        for s in analysis.strengths:
            key = s.lower()[:45]
            if key not in seen:
                seen.add(key)
                strengths.append(f"Resume strength: {s}")

    return strengths[:_MAX_STRENGTHS]


def _extract_improvements(answers: list[dict], analysis, role: str) -> list[str]:
    freq: dict[str, int] = {}
    raw:  dict[str, str] = {}

    for a in answers:
        for pt in a["evaluation"].get("missing_points", []):
            key = pt.lower()[:60]
            freq[key] = freq.get(key, 0) + 1
            raw.setdefault(key, pt)

    sorted_keys  = sorted(freq, key=lambda k: -freq[k])
    seen: set[str] = set()
    improvements: list[str] = []

    for key in sorted_keys:
        if key not in seen:
            seen.add(key)
            improvements.append(raw[key])

    if analysis and hasattr(analysis, "weak_areas"):
        for wa in analysis.weak_areas:
            key = wa.lower()[:45]
            if key not in seen:
                seen.add(key)
                improvements.append(f"Knowledge gap from resume: {wa}")

    return improvements[:_MAX_IMPROVEMENTS]


# ── Learning plan ─────────────────────────────────────────────────────────────

def _build_learning_plan(
    weak_topics: list[str],
    improvements: list[str],
) -> list[LearningItem]:
    plan:             list[LearningItem] = []
    added_resources:  set[str]          = set()

    def _add(topic: str, info: dict) -> bool:
        if len(plan) >= _MAX_LEARNING or info["resource"] in added_resources:
            return False
        added_resources.add(info["resource"])
        plan.append(LearningItem(
            topic=topic,
            resource=info["resource"],
            reason=info["reason"],
            priority=info["priority"],
        ))
        return True

    # 1 — Direct weak-topic resources
    for topic in weak_topics:
        if info := _TOPIC_RESOURCES.get(topic):
            _add(topic, info)

    # 2 — Keyword match from improvement point text
    for imp in improvements:
        if len(plan) >= _MAX_LEARNING:
            break
        imp_lower = imp.lower()
        for topic, info in _TOPIC_RESOURCES.items():
            if any(w in imp_lower for w in topic.lower().split()):
                if _add(topic, info):
                    break

    # 3 — Generic fallback
    if not plan:
        plan.append(LearningItem(
            topic="General",
            resource=_GENERIC_RESOURCE["resource"],
            reason=_GENERIC_RESOURCE["reason"],
            priority=_GENERIC_RESOURCE["priority"],
        ))

    # Sort by priority: high → medium → low
    _order = {"high": 0, "medium": 1, "low": 2}
    plan.sort(key=lambda item: _order.get(item.priority, 3))
    return plan[:_MAX_LEARNING]


# ── Feedback text ─────────────────────────────────────────────────────────────

def _rule_feedback(
    tech: int, comm: int, conf: int, eng: int,
    role_fit: int, overall: int,
    role: str, strengths: list[str], improvements: list[str],
    session_data: dict | None = None,
    analysis=None,
    audio_scores: list | None = None,
) -> str:
    """
    Flowing multi-paragraph narrative feedback.

    Structure:
      ¶1 — Performance overview: role, overall score, fit, inferred level
      ¶2 — Strongest moment: best topic with concrete evidence
      ¶3 — Key weakness: what was missed and why it matters for the role
      ¶4 — Communication coaching (audio) + behavioural observation
      ¶5 — Action plan: project hook + single concrete next step
    """
    level_adj = "strong" if tech >= 70 else "solid" if tech >= 55 else "developing"
    fit_desc  = "excellent" if role_fit >= 80 else "good" if role_fit >= 65 else "emerging"
    readiness = (
        "ready to compete at this level" if overall >= 72 and tech >= 68
        else "approaching readiness" if overall >= 58
        else "still building the depth needed"
    )

    # Candidate first name
    name = ""
    if analysis and getattr(analysis, "candidate_name", ""):
        name = analysis.candidate_name.strip().split()[0]
    salutation = f"{name}, you" if name else "You"

    # Gather per-topic performance for paragraphs 2 & 3
    strong_topics: list[tuple[str, int]] = []
    weak_topics:   list[tuple[str, int]] = []
    if session_data:
        answers   = session_data.get("answers", [])
        questions = session_data.get("questions_asked", [])
        q_by_id   = {q["question_id"]: q for q in questions}
        for a in answers:
            matched_q = q_by_id.get(a.get("question_id", ""))
            topic = (matched_q.get("topic", "") if matched_q else "").strip()
            score = a["evaluation"]["technical_score"]
            if topic and "Behavioral" not in topic and "Follow-Up" not in topic:
                if score >= 70:
                    strong_topics.append((topic, score))
                elif score < 55:
                    weak_topics.append((topic, score))

    best_topic  = max(strong_topics, key=lambda x: x[1]) if strong_topics else None
    worst_topic = min(weak_topics,   key=lambda x: x[1]) if weak_topics   else None

    # ── Paragraph 1: Performance overview ────────────────────────────────────
    p1 = (
        f"{salutation} completed the mock interview for the {role} role and demonstrated "
        f"{level_adj} technical proficiency, finishing with an overall score of {overall}/100. "
        f"Your background shows {fit_desc} alignment with this role (fit score: {role_fit}/100), "
        f"and based on the answers across all topics, you appear {readiness}."
    )

    # ── Paragraph 2: Strongest moment ────────────────────────────────────────
    if best_topic:
        covered_pts = []
        if session_data:
            for a in session_data.get("answers", []):
                q = q_by_id.get(a.get("question_id", ""))
                t = (q.get("topic", "") if q else "").strip()
                if t == best_topic[0]:
                    covered_pts = a["evaluation"].get("covered_points", [])[:2]
                    break
        evidence = (
            f", specifically covering {' and '.join(covered_pts)}" if covered_pts
            else ""
        )
        p2 = (
            f"Your strongest moment came on {best_topic[0]} (scored {best_topic[1]}/100){evidence}. "
            "This is exactly the kind of grounded, well-articulated answer that stands out to "
            "hiring panels — keep that level of specificity as a benchmark for every topic."
        )
    elif strengths:
        p2 = (
            f"You demonstrated the clearest command of '{strengths[0]}', "
            "hitting the core concepts interviewers look for at this level. "
            "Use that response as a template: specific, reasoned, and backed by context."
        )
    else:
        p2 = (
            "Across the session you showed a willingness to reason through unfamiliar territory, "
            "which is a signal interviewers value even when an answer isn't perfect."
        )

    # ── Paragraph 3: Key weakness ─────────────────────────────────────────────
    if worst_topic:
        missed = []
        if session_data:
            for a in session_data.get("answers", []):
                q = q_by_id.get(a.get("question_id", ""))
                t = (q.get("topic", "") if q else "").strip()
                if t == worst_topic[0]:
                    missed = a["evaluation"].get("missing_points", [])[:2]
                    break
        missed_text = (
            f" — particularly {' and '.join(missed)}" if missed else ""
        )
        p3 = (
            f"The area that needs the most attention before your next interview is {worst_topic[0]} "
            f"(scored {worst_topic[1]}/100{missed_text}). "
            f"For a {role} role, interviewers treat this as a core competency, so a gap here "
            "will surface in every hiring loop. The learning plan below targets it directly."
        )
    elif improvements:
        p3 = (
            f"The most impactful gap to close is: '{improvements[0]}'. "
            f"This concept comes up consistently in {role} interviews and "
            "shoring it up will meaningfully improve your close rate."
        )
    else:
        p3 = (
            "No single topic stood out as a critical gap — the main opportunity is "
            "deepening every answer with trade-off reasoning and concrete examples, "
            "which will lift your scores from good to exceptional."
        )

    # ── Paragraph 4: Communication coaching + behavioural observation ─────────
    comm_lines: list[str] = []

    if audio_scores:
        real_audio = [a for a in audio_scores if a.get("mode") in ("faster_whisper", "whisper")]
        if real_audio:
            avg_wpm    = sum(a.get("words_per_minute", 130) or 130 for a in real_audio) / len(real_audio)
            avg_filler = sum(a.get("filler_ratio", 0) or 0 for a in real_audio) / len(real_audio)
            hi_hesit   = sum(1 for a in real_audio if a.get("hesitation_level") == "high")

            if avg_wpm > 175:
                comm_lines.append(
                    f"your speaking pace averaged ~{round(avg_wpm)} WPM — slightly faster than ideal; "
                    "deliberately pausing at key transitions gives the interviewer time to absorb complex points"
                )
            elif avg_wpm < 95:
                comm_lines.append(
                    f"at ~{round(avg_wpm)} WPM your delivery was slower than typical; "
                    "a slightly brisker pace maintains momentum and signals confidence"
                )
            if avg_filler > 0.08:
                comm_lines.append(
                    f"filler words accounted for ~{round(avg_filler * 100)}% of speech — "
                    "replacing 'um' and 'uh' with a one-second silence sounds far more decisive"
                )
            if hi_hesit > len(real_audio) // 2:
                comm_lines.append(
                    "there were frequent mid-answer pauses; try the 'think → speak' habit: "
                    "take 3 seconds of silence before answering rather than thinking aloud"
                )

    if comm_lines:
        intro = "On the communication side, "
        p4 = intro + "; ".join(comm_lines) + ". "
    else:
        p4 = ""

    # Add behavioural observation regardless
    if tech >= 70 and conf >= 70:
        p4 += (
            "Your answers combined technical accuracy with confident, well-paced delivery — "
            "that combination is rare and genuinely memorable in real panels."
        )
    elif tech >= 70:
        p4 += (
            "Your technical knowledge is solid; the next frontier is projecting that "
            "knowledge with the same certainty you demonstrate when writing it down. "
            "Record yourself answering one question per day — the gap closes quickly."
        )
    elif conf >= 70:
        p4 += (
            "Your delivery came across as assured and engaging. "
            "Channelling that presence into deeper technical specifics will "
            "significantly raise your hiring signal."
        )
    else:
        p4 += (
            "Structured practice — answering aloud, timing yourself, and reviewing the recording — "
            "is the single fastest way to raise both your technical clarity and your delivery confidence."
        )

    # ── Paragraph 5: Action plan with project hook ────────────────────────────
    proj_hook = ""
    if analysis and getattr(analysis, "projects", []):
        proj  = analysis.projects[0]
        techs = ", ".join(proj.technologies[:2]) if proj.technologies else "your primary stack"
        proj_hook = (
            f"Your '{proj.name}' project (built with {techs}) is your strongest interview asset — "
            "practise narrating its architecture, your personal contributions, and one specific "
            "trade-off decision in under 90 seconds. "
        )

    next_step = (
        f"Start with the top-priority resource in the learning plan below"
        + (f", and then revisit {worst_topic[0]} with a timed practice question" if worst_topic else "")
        + ". "
        "Technical interview performance compounds: consistent deliberate practice over two weeks "
        "produces more improvement than a single intensive cram session."
    )

    p5 = proj_hook + next_step

    # Assemble — skip empty paragraphs
    paragraphs = [p for p in [p1, p2, p3, p4, p5] if p.strip()]
    return "\n\n".join(paragraphs)


async def _llm_feedback(
    session_data: dict, analysis,
    role: str, scores: dict,
    strengths: list[str], improvements: list[str],
) -> str | None:
    from config import get_settings
    settings = get_settings()
    if not settings.has_llm_configured:
        return None
    try:
        from services.llm_client import call_llm
        qa_lines = "\n".join(
            f"Q{i+1} [{a.get('question','')[:55]}…]: "
            f"Technical={a['evaluation']['technical_score']}, "
            f"Depth={a['evaluation']['depth_score']}, "
            f"Covered={len(a['evaluation'].get('covered_points', []))} points"
            for i, a in enumerate(session_data.get("answers", []))
        )
        name = (analysis.candidate_name if analysis else "") or "the candidate"
        prompt = (
            f"You are a senior technical hiring manager writing a final interview report.\n\n"
            f"Candidate: {name}\n"
            f"Role: {role}\n"
            f"Scores — Overall: {scores['overall']}/100 | Technical: {scores['technical']}/100 | "
            f"Communication: {scores['comm']}/100 | Confidence: {scores['conf']}/100 | "
            f"Engagement: {scores['eng']}/100 | Role Fit: {scores['role_fit']}/100\n\n"
            f"Q&A summary:\n{qa_lines}\n\n"
            f"Key strengths: {', '.join(strengths[:3]) or 'none identified'}\n"
            f"Areas to improve: {', '.join(improvements[:3]) or 'none identified'}\n\n"
            "Write 3-4 paragraphs of personalised final feedback. Be encouraging but honest. "
            "Name specific topics they covered well and specific gaps to address. "
            "End with one concrete actionable next step. Plain prose — no bullets, no headings."
        )
        result = await call_llm(prompt, max_tokens=650)
        return result.strip() if result else None
    except Exception as exc:
        logger.warning("LLM final feedback failed: %s", exc)
    return None


# ── Phase 11: Diagnostic builder ─────────────────────────────────────────────

_ALL_ROLES = [
    "Full Stack Developer", "Frontend Developer", "Backend Developer",
    "Data Scientist", "ML / AI Engineer", "DevOps / Cloud Engineer",
    "Mobile Developer", "Data Engineer",
]

_ROLE_CORE_SKILLS: dict[str, list[str]] = {
    "Full Stack Developer":    ["REST APIs", "Database Design", "Authentication", "React", "System Design"],
    "Frontend Developer":      ["React", "CSS", "State Management", "Performance", "Accessibility"],
    "Backend Developer":       ["API Design", "Database", "Security", "Concurrency", "System Design"],
    "Data Scientist":          ["Machine Learning", "Statistics", "Python", "Model Evaluation", "Data Analysis"],
    "ML / AI Engineer":        ["Deep Learning", "MLOps", "Model Serving", "Python", "Transformers"],
    "DevOps / Cloud Engineer": ["Kubernetes", "Docker", "CI/CD", "Cloud Architecture", "Observability"],
    "Mobile Developer":        ["React Native", "iOS/Android APIs", "Performance", "Offline Architecture"],
    "Data Engineer":           ["Pipelines", "Spark", "Kafka", "Data Quality", "Data Modelling"],
}


def _build_diagnostic(
    session_data: dict,
    answers: list[dict],
    overall: int,
    tech: int,
    role: str,
    role_fit: int,
    strengths: list[str],
    improvements: list[str],
    analysis,
) -> dict:
    """Build the Phase 11 diagnostic coaching section."""

    # ── Readiness level ───────────────────────────────────────────────────────
    if overall >= 72 and tech >= 68 and role_fit >= 70:
        readiness_level = "ready"
    elif overall >= 58 or tech >= 55:
        readiness_level = "almost_ready"
    else:
        readiness_level = "needs_practice"

    # ── Best fit roles ────────────────────────────────────────────────────────
    resume_skills: set[str] = set()
    if analysis:
        for s in getattr(analysis, "skills", []):
            resume_skills.add(s.lower())

    best_fit: list[str] = []
    for r in _ALL_ROLES:
        core = _ROLE_CORE_SKILLS.get(r, [])
        overlap = sum(
            1 for c in core
            if any(c.lower() in rs or rs in c.lower() for rs in resume_skills)
        )
        if overlap >= 2:
            best_fit.append(r)
    if not best_fit:
        best_fit = [role]
    # Put the selected role first
    if role in best_fit:
        best_fit = [role] + [r for r in best_fit if r != role]
    best_fit = best_fit[:3]

    # ── Weaker role risks ─────────────────────────────────────────────────────
    weak_areas = getattr(analysis, "weak_areas", []) if analysis else []
    weaker_risks: list[str] = []
    for wa in weak_areas[:3]:
        weaker_risks.append(
            f"Limited depth in '{wa}' may affect performance in roles requiring it"
        )
    if tech < 55:
        weaker_risks.append(
            "Technical score below threshold for senior-level positions without further study"
        )

    # ── Skill mastery summary from candidate state ────────────────────────────
    raw_state = session_data.get("candidate_state")
    skill_mastery_summary: dict[str, int] = {}
    if raw_state:
        skill_mastery_summary = raw_state.get("skill_mastery", {})
    if not skill_mastery_summary:
        # Build from answer evaluations
        questions = session_data.get("questions_asked", [])
        q_by_id = {q["question_id"]: q for q in questions}
        for a in answers:
            matched_q = q_by_id.get(a.get("question_id", ""))
            if matched_q:
                t = matched_q.get("topic", "")
                if t:
                    skill_mastery_summary[t] = a["evaluation"]["technical_score"]

    # ── Top 3 strengths with evidence ─────────────────────────────────────────
    top_strengths_ev: list[str] = []
    for a in answers:
        covered = a["evaluation"].get("covered_points", [])
        tech_s = a["evaluation"]["technical_score"]
        if tech_s >= 65 and covered:
            ev = covered[0]
            top_strengths_ev.append(f"Demonstrated '{ev}' with a score of {tech_s}/100")
        if len(top_strengths_ev) >= 3:
            break
    if not top_strengths_ev and strengths:
        top_strengths_ev = [f"Resume strength: {s}" for s in strengths[:3]]

    # ── Top 3 gaps with evidence ──────────────────────────────────────────────
    top_gaps_ev: list[str] = []
    freq: dict[str, int] = {}
    raw_missing: dict[str, str] = {}
    for a in answers:
        for pt in a["evaluation"].get("missing_points", []):
            k = pt.lower()[:50]
            freq[k] = freq.get(k, 0) + 1
            raw_missing.setdefault(k, pt)
    for k in sorted(freq, key=lambda x: -freq[x])[:3]:
        top_gaps_ev.append(
            f"Missed '{raw_missing[k]}'"
            + (f" (appeared in {freq[k]} answer{'s' if freq[k] > 1 else ''})" if freq[k] > 1 else "")
        )
    if not top_gaps_ev and improvements:
        top_gaps_ev = [f"Area to improve: {imp}" for imp in improvements[:3]]

    # ── 7-day practice plan ───────────────────────────────────────────────────
    weak_topics = [t for t, v in skill_mastery_summary.items() if v < 55][:3]
    plan_7_day: list[str] = [
        f"Day 1-2: Review core concepts for '{weak_topics[0]}' — focus on definitions and examples"
        if weak_topics else
        f"Day 1-2: Revisit {role} fundamentals using the recommended learning resources",

        f"Day 3-4: Build or extend a project that demonstrates "
        f"{'and '.join(weak_topics[:2]) if weak_topics else 'core skills from this session'}",

        "Day 5: Practice explaining your projects out loud — use the STAR method (Situation, Task, Action, Result)",

        "Day 6: Run 2 timed mock questions (15 min each) using the question banks linked below",

        "Day 7: Record yourself answering one hard question — review audio/video for confidence and clarity",
    ]
    # Add specific topic hint if available
    if len(weak_topics) >= 2:
        plan_7_day.insert(1,
            f"Day 2 (bonus): Watch one focused tutorial on '{weak_topics[1]}' — "
            "aim to be able to explain it in 90 seconds without notes"
        )
        plan_7_day = plan_7_day[:7]

    # ── Adaptation summary ────────────────────────────────────────────────────
    adaptation_log = session_data.get("adaptation_log", [])
    decision_traces = session_data.get("decision_traces", [])
    adaptation_summary: list[str] = []

    if decision_traces:
        for trace in decision_traces[:4]:
            dt = trace.get("decision_type", "")
            prev = trace.get("previous_topic", "")
            score = trace.get("previous_score", 0)
            next_t = trace.get("next_topic", "")
            if dt == "increase_difficulty":
                adaptation_summary.append(
                    f"After strong performance on '{prev}' ({score}/100), difficulty increased for '{next_t}'"
                )
            elif dt == "strengthen_fundamentals":
                adaptation_summary.append(
                    f"Score of {score}/100 on '{prev}' triggered a return to foundational concepts in '{next_t}'"
                )
            elif dt == "remediation":
                adaptation_summary.append(
                    f"Repeated weakness on '{prev}' → remediation probe on '{next_t}'"
                )
            elif dt == "deeper_follow_up":
                adaptation_summary.append(
                    f"Solid answer on '{prev}' ({score}/100) → follow-up depth probe in '{next_t}'"
                )
            elif dt == "confidence_recovery":
                adaptation_summary.append(
                    f"Confidence recovery triggered after '{prev}' — easier entry point on '{next_t}'"
                )
    elif adaptation_log:
        adaptation_summary = [f"Q{i+2}: {r}" for i, r in enumerate(adaptation_log[:4])]

    if not adaptation_summary:
        adaptation_summary = ["Session used standard difficulty progression — no significant adaptation triggered"]

    return {
        "readiness_level": readiness_level,
        "best_fit_roles": best_fit,
        "weaker_role_risks": weaker_risks,
        "skill_mastery_summary": skill_mastery_summary,
        "top_3_strengths_with_evidence": top_strengths_ev,
        "top_3_gaps_with_evidence": top_gaps_ev,
        "recommended_7_day_plan": plan_7_day,
        "adaptation_summary": adaptation_summary,
    }


# ── Main entry point ──────────────────────────────────────────────────────────

async def generate_report(
    session_data: dict,
    analysis,            # ResumeAnalysis | None
    role_match_score: int,
) -> FinalReport:
    answers         = session_data.get("answers", [])
    questions       = session_data.get("questions_asked", [])
    role            = session_data.get("selected_role", "")
    candidate_id    = session_data.get("candidate_id", "")
    adaptation_log  = session_data.get("adaptation_log", [])
    audio_scores    = session_data.get("audio_scores", [])
    video_scores    = session_data.get("video_scores", [])

    # ── Scores ────────────────────────────────────────────────────────────────
    tech = _compute_technical_score(answers)
    role_fit = role_match_score

    # Heuristic baseline (always computed; overridden per-axis when real data exists)
    comm_h, conf_h, eng_h = _compute_behavioral_scores(answers)

    from statistics import mean as _mean

    # Communication & Confidence — from audio when available
    comm = round(_mean([a["communication_clarity_score"] for a in audio_scores])) if audio_scores else comm_h
    conf = round(_mean([a["confidence_score"]            for a in audio_scores])) if audio_scores else conf_h

    # Engagement — from video when available; skip invalid_analysis entries
    valid_video = [
        v for v in video_scores
        if v.get("status") != "invalid_analysis" and v.get("engagement_score") is not None
    ]
    eng = round(_mean([v["engagement_score"] for v in valid_video])) if valid_video else eng_h

    # ── Behavioral mode label ─────────────────────────────────────────────────
    audio_real = any(a.get("mode") in ("faster_whisper", "whisper")       for a in audio_scores)
    video_real = any(v.get("mode") in ("opencv_mediapipe", "opencv")      for v in video_scores)

    if audio_scores and video_scores:
        behavioral_mode = "multimodal"
    elif audio_scores:
        behavioral_mode = "audio"          if audio_real else "audio_fallback"
    elif video_scores:
        behavioral_mode = "video"          if video_real else "video_fallback"
    else:
        behavioral_mode = "placeholder"

    overall = round(tech * 0.45 + comm * 0.20 + conf * 0.15 + eng * 0.10 + role_fit * 0.10)

    # ── Qualitative analysis ──────────────────────────────────────────────────
    strengths    = _extract_strengths(answers, analysis)
    improvements = _extract_improvements(answers, analysis, role)

    # Topics where technical score was below threshold
    q_by_id = {q["question_id"]: q for q in questions}
    weak_topics: list[str] = []
    for a in answers:
        if a["evaluation"]["technical_score"] < 60:
            matched = q_by_id.get(a.get("question_id", ""))
            if matched:
                t = matched.get("topic", "")
                if t and t not in weak_topics:
                    weak_topics.append(t)

    learning_plan = _build_learning_plan(weak_topics, improvements)

    # ── Final feedback ────────────────────────────────────────────────────────
    scores_dict = {
        "overall": overall, "technical": tech,
        "comm": comm, "conf": conf, "eng": eng, "role_fit": role_fit,
    }
    final_feedback = await _llm_feedback(
        session_data, analysis, role, scores_dict, strengths, improvements
    )
    final_feedback_source = "rule_based_fallback"
    if not final_feedback:
        final_feedback = _rule_feedback(
            tech, comm, conf, eng, role_fit, overall, role, strengths, improvements,
            session_data=session_data,
            analysis=analysis,
            audio_scores=audio_scores,
        )
    else:
        from config import get_settings
        final_feedback_source = f"llm:{get_settings().llm_provider.lower()}"

    # ── Answer summaries ──────────────────────────────────────────────────────
    # adaptation_log[i] is why question i+2 was chosen
    # (index 0 = reason for Q2, index 1 = reason for Q3, etc.)
    # question_number → entry lookups for audio and video
    audio_by_q: dict[int, dict] = {
        a["question_number"]: a
        for a in audio_scores
        if a.get("question_number") is not None
    }
    video_by_q: dict[int, dict] = {
        v["question_number"]: v
        for v in video_scores
        if v.get("question_number") is not None
    }

    answer_summaries: list[AnswerSummary] = []
    for idx, a in enumerate(answers):
        matched_q = q_by_id.get(a.get("question_id", ""))
        if not matched_q and idx < len(questions):
            matched_q = questions[idx]

        q_num        = idx + 1
        adapt_reason = adaptation_log[idx - 1] if 0 < idx <= len(adaptation_log) else None
        audio_entry  = audio_by_q.get(q_num)
        video_entry  = video_by_q.get(q_num)

        answer_summaries.append(AnswerSummary(
            question_number=q_num,
            question=a.get("question", matched_q["question"] if matched_q else ""),
            topic=matched_q["topic"]           if matched_q else "",
            difficulty=matched_q["difficulty"] if matched_q else "",
            technical_score=a["evaluation"]["technical_score"],
            depth_score=a["evaluation"]["depth_score"],
            correctness_score=a["evaluation"]["correctness_score"],
            covered_points=a["evaluation"].get("covered_points", []),
            missing_points=a["evaluation"].get("missing_points", []),
            adaptation_reason=adapt_reason,
            # Audio intelligence
            audio_transcript=   audio_entry.get("transcript")                  if audio_entry else None,
            audio_confidence=   audio_entry.get("confidence_score")            if audio_entry else None,
            audio_clarity=      audio_entry.get("communication_clarity_score") if audio_entry else None,
            audio_speaking_rate=audio_entry.get("speaking_rate")               if audio_entry else None,
            audio_pause_count=  audio_entry.get("pause_count")                 if audio_entry else None,
            # Video intelligence
            video_engagement=   video_entry.get("engagement_score")  if video_entry else None,
            video_framing=      video_entry.get("framing_score")     if video_entry else None,
            video_stability=    video_entry.get("stability_score")   if video_entry else None,
            video_movement=     video_entry.get("movement_activity") if video_entry else None,
        ))

    candidate_name = (
        analysis.candidate_name if (analysis and hasattr(analysis, "candidate_name"))
        else ""
    ) or "Candidate"

    # ── Phase 11: Diagnostic coaching section ─────────────────────────────────
    diagnostic = _build_diagnostic(
        session_data=session_data,
        answers=answers,
        overall=overall,
        tech=tech,
        role=role,
        role_fit=role_fit,
        strengths=strengths,
        improvements=improvements,
        analysis=analysis,
    )

    return FinalReport(
        session_id=session_data.get("session_id", ""),
        candidate_id=candidate_id,
        candidate_name=candidate_name,
        selected_role=role,
        generated_at=datetime.now(timezone.utc),
        overall_score=overall,
        technical_score=tech,
        communication_score=comm,
        confidence_score=conf,
        engagement_score=eng,
        role_fit_score=role_fit,
        behavioral_mode=behavioral_mode,
        strengths=strengths,
        improvement_areas=improvements,
        recommended_learning_plan=learning_plan,
        final_feedback=final_feedback,
        final_feedback_source=final_feedback_source,
        answer_summaries=answer_summaries,
        **diagnostic,
    )
